### ISSUE TITLE
I'm on V125 and did the instructions ... but when I set the name servers - I did absolutely NOTHING ...

### ISSUE THREAD

**Issue by ghost** [S-PScripts/incognito-v123#1]
help ...

**Comment by S-PScripts** [comment]
you might need to disconnect and reconnect and change the name servers again for it to work.

**Comment by Egduffuu** [comment]
wdym? "reconnect and disconnect"? and do I change the name servers to what you said?

**Comment by S-PScripts** [comment]
turn off and on your wifi. change the custom name servers back to detectportal.firefox.com OR captive.apple.com OR 150.136.163.0 since it will revert to 0.0.0.0 upon turning off and on your wifi

**Comment by Egduffuu** [comment]
it works, but since there is no wifi when I am in incog, it legit does nothing ...

**Comment by S-PScripts** [comment]
> it works, but since there is no wifi when I am in incog, it legit does nothing ...

You need to change the name servers back to automatic first! After this, disconnect and reconnect to your wifi.

**Comment by Egduffuu** [comment]
ok ... it works, but sites are still blocked bcuz of DNS. its kinda useless

**Comment by Egduffuu** [comment]
and I already have ways to unblock youtube

**Comment by S-PScripts** [comment]
> ok ... it works, but sites are still blocked bcuz of DNS. its kinda useless

a dns block... that's unfortunate
